FROM apache/nifi:1.27.0

USER root

RUN apt-get update && apt-get install -y vim uuid-runtime

COPY ./nifi_project/conf/authorizations.xml /opt/nifi/nifi-current/conf/authorizations.xml

COPY ./nifi_project/conf/update-authorizations.sh /opt/nifi/nifi-current/conf/update-authorizations.sh

COPY ./nifi_custom_processor/another_custom_kafka_streaming/nifi-another_custom_kafka_streaming-nar/target/nifi-another_custom_kafka_streaming-nar-1.0-nar /opt/nifi/nifi-current/lib/

COPY ./nifi_custom_processor/my-custom-consumekaffka-processor/nifi-custom_consumekafka-nar/target/nifi-custom_consumekafka-nar-1.0-nar /opt/nifi/nifi-current/lib/

EXPOSE 8443
