FROM apache/nifi:1.27.0

USER root

RUN apt-get update && apt-get install -y vim uuid-runtime

COPY ./nifi_project/conf/authorizations.xml /opt/nifi/nifi-current/conf/authorizations.xml

COPY ./nifi_project/conf/update-authorizations.sh /opt/nifi/nifi-current/conf/update-authorizations.sh

EXPOSE 8443
